### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by emmak4j** [SuperFola/TierListMaker#2]
Step I have done :
- Download the source code from ZIP
- Start the project lunching inde.html

The problem I encountered is that assets files don't load :
![image](https://user-images.githubusercontent.com/64542271/125288138-12de1380-e31e-11eb-8285-9732286f7d01.png)

Pre-fix :
- remove the `/` for import in HTML, for example :
```
<script src="/assets/js/utils.js" defer></script> // old one
<script src="assets/js/utils.js" defer></script> // new one
```

Result :
![image](https://user-images.githubusercontent.com/64542271/125288615-a1529500-e31e-11eb-860e-51ef053adf37.png)

There are still problems, some components are not loading!
The console in my navigator (sorry it's in french but as you are french, I think it's okay).
![image](https://user-images.githubusercontent.com/64542271/125288850-e1b21300-e31e-11eb-8b6b-a2c2163463a0.png)

Note :
- The problem might be on my side.
- For information, I used Mozilla Firefox Version 88.0.1 (64 bits).

**Comment by SuperFola** [comment]
Hi, the icons don't load because I set font awesome to load only from my domain (12f.pl) instead of embedding directly font awesome inside the project.

How do you launch the project? By launching a web server using `python -m http.server`, it works like a charm (even with the starting `/`).

This might be a problem (working only on my website) so this is definetly something that needs to change

**Comment by emmak4j** [comment]
Hi 😄 ,

So this is totally my fault, I was launching the project by double-clicking on the index.html because I thought it could be lunch like this. By launching a web server using `python -m http.server` as you said, work 100% fine without changing anything to your project (you might consider putting the lunch instruction in the readme because stupid like me will do as I have done 😄 ).

**Comment by My1** [comment]
relative paths would still be nice for just deploying it on an existing web server.

**Comment by SuperFola** [comment]
I'm not using the project anymore and don't really time to do it, but I'm open to a PR
