### ISSUE TITLE
Feature request: Tier customization

### ISSUE THREAD

**Issue by DrewUniverse** [SuperFola/TierListMaker#6]
Hi there. Would you be willing to add some customizations for tiers?  I don't know how hard this would be to add, and I realize this is an old project, so no worries if the answer is no. In order of request:

1. allow custom text for each tier name. 
2. Dark mode toggle.
3. Choose color for tier name backgrounds.

I really like being able to use an offline tool for tier lists - thank you so much for creating this project!

**Comment by SuperFola** [comment]
Hello! Sorry for the delay

I don't have much time to continue contributing to opensource with work and life happening, however I'm open to pull requests!

Thanks for your interest in this little project, I'm glad to hear this is useful to some people
